Fix for 404 error get_deals_and_orders(). #102
Qluxzz/avanza pull request #105
Opened 2024-06-24 17:38 UTC by Unt3r

I found two new links.
One for deals and one for orders.
Added two new methods and path.

Instead of calling get_deals_and_orders() you either call get_deals() or get_orders()

2024-06-24 17:40 UTC, Unt3r commented
Fix to issue #102.

First try to make a pull request so I hope it works. :)

2024-06-24 19:29 UTC, Qluxzz requested changes

2024-06-24 19:29 UTC, Qluxzz commented on avanza/avanza.py
> +    """ Get currently active orders """
This comment is wrongly indented, should be indented to be in line with the code.

2024-06-24 19:29 UTC, Qluxzz commented on avanza/constants.py
>      DEALS_AND_ORDERS_PATH = "/_mobile/account/dealsandorders"
Remove this since it doesn't work, and remove function from avanza.py as well.

2024-06-25 18:13 UTC, Unt3r commented
I made the changes. Not sure if I need to do anything more...

2024-06-25 19:05 UTC, merged

2024-06-25 19:05 UTC, Qluxzz commented
It looks great, thanks for contributing!